<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing CustomHeaderAuthentication security credentials.
 */
class CustomHeaderAuthenticationCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for CustomHeaderAuthenticationCredentialsBuilder
     *
     * @param string $authorization
     */
    public static function init(string $authorization): self
    {
        return new self(['authorization' => $authorization]);
    }

    /**
     * Setter for Authorization.
     *
     * @param string $authorization
     *
     * @return $this
     */
    public function authorization(string $authorization): self
    {
        $this->config['authorization'] = $authorization;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
