<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Authentication;

use Core\Authentication\CoreAuth;
use ReportingAuthorizationSummaryApiLib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;
use ReportingAuthorizationSummaryApiLib\CustomHeaderAuthenticationCredentials;

/**
 * Utility class for authorization and token management.
 */
class CustomHeaderAuthenticationManager extends CoreAuth implements CustomHeaderAuthenticationCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(HeaderParam::init('Authorization', $this->getAuthorization())->requiredNonEmpty());
    }

    /**
     * String value for authorization.
     */
    public function getAuthorization(): string
    {
        return $this->config['authorization'] ?? ConfigurationDefaults::AUTHORIZATION;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization ``` License format is WORLDPAY license='xxxx'```
     */
    public function equals(string $authorization): bool
    {
        return $authorization == $this->getAuthorization();
    }
}
