<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\AuthTransactionsSummaryRequestByTransactionDate;
use ReportingAuthorizationSummaryApiLib\Models\DateRange;
use ReportingAuthorizationSummaryApiLib\Models\Entity;
use ReportingAuthorizationSummaryApiLib\Models\Pagination;

/**
 * Builder for model AuthTransactionsSummaryRequestByTransactionDate
 *
 * @see AuthTransactionsSummaryRequestByTransactionDate
 */
class AuthTransactionsSummaryRequestByTransactionDateBuilder
{
    /**
     * @var AuthTransactionsSummaryRequestByTransactionDate
     */
    private $instance;

    private function __construct(AuthTransactionsSummaryRequestByTransactionDate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Auth Transactions Summary Request By Transaction Date Builder object.
     *
     * @param Entity $hierarchy
     * @param DateRange $dateRange
     */
    public static function init(Entity $hierarchy, DateRange $dateRange): self
    {
        return new self(new AuthTransactionsSummaryRequestByTransactionDate($hierarchy, $dateRange));
    }

    /**
     * Sets pagination field.
     *
     * @param Pagination|null $value
     */
    public function pagination(?Pagination $value): self
    {
        $this->instance->setPagination($value);
        return $this;
    }

    /**
     * Sets card Type field.
     *
     * @param string|null $value
     */
    public function cardType(?string $value): self
    {
        $this->instance->setCardType($value);
        return $this;
    }

    /**
     * Sets card Networks field.
     *
     * @param string[]|null $value
     */
    public function cardNetworks(?array $value): self
    {
        $this->instance->setCardNetworks($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Auth Transactions Summary Request By Transaction Date object.
     */
    public function build(): AuthTransactionsSummaryRequestByTransactionDate
    {
        return CoreHelper::clone($this->instance);
    }
}
