<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\AuthorizationsSummaryTransactiondateResponse;
use ReportingAuthorizationSummaryApiLib\Models\PaginationResponse;
use ReportingAuthorizationSummaryApiLib\Models\Summary1;

/**
 * Builder for model AuthorizationsSummaryTransactiondateResponse
 *
 * @see AuthorizationsSummaryTransactiondateResponse
 */
class AuthorizationsSummaryTransactiondateResponseBuilder
{
    /**
     * @var AuthorizationsSummaryTransactiondateResponse
     */
    private $instance;

    private function __construct(AuthorizationsSummaryTransactiondateResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Authorizations Summary Transactiondate Response Builder object.
     */
    public static function init(): self
    {
        return new self(new AuthorizationsSummaryTransactiondateResponse());
    }

    /**
     * Sets pagination field.
     *
     * @param PaginationResponse|null $value
     */
    public function pagination(?PaginationResponse $value): self
    {
        $this->instance->setPagination($value);
        return $this;
    }

    /**
     * Sets total Approved Count field.
     *
     * @param int|null $value
     */
    public function totalApprovedCount(?int $value): self
    {
        $this->instance->setTotalApprovedCount($value);
        return $this;
    }

    /**
     * Sets total Approved Amount field.
     *
     * @param float|null $value
     */
    public function totalApprovedAmount(?float $value): self
    {
        $this->instance->setTotalApprovedAmount($value);
        return $this;
    }

    /**
     * Sets total Declined Count field.
     *
     * @param int|null $value
     */
    public function totalDeclinedCount(?int $value): self
    {
        $this->instance->setTotalDeclinedCount($value);
        return $this;
    }

    /**
     * Sets total Declined Amount field.
     *
     * @param float|null $value
     */
    public function totalDeclinedAmount(?float $value): self
    {
        $this->instance->setTotalDeclinedAmount($value);
        return $this;
    }

    /**
     * Sets total Approved Count Percent field.
     *
     * @param float|null $value
     */
    public function totalApprovedCountPercent(?float $value): self
    {
        $this->instance->setTotalApprovedCountPercent($value);
        return $this;
    }

    /**
     * Sets total Approved Amount Percent field.
     *
     * @param float|null $value
     */
    public function totalApprovedAmountPercent(?float $value): self
    {
        $this->instance->setTotalApprovedAmountPercent($value);
        return $this;
    }

    /**
     * Sets total Declined Count Percent field.
     *
     * @param float|null $value
     */
    public function totalDeclinedCountPercent(?float $value): self
    {
        $this->instance->setTotalDeclinedCountPercent($value);
        return $this;
    }

    /**
     * Sets total Declined Amount Percent field.
     *
     * @param float|null $value
     */
    public function totalDeclinedAmountPercent(?float $value): self
    {
        $this->instance->setTotalDeclinedAmountPercent($value);
        return $this;
    }

    /**
     * Sets total Count field.
     *
     * @param int|null $value
     */
    public function totalCount(?int $value): self
    {
        $this->instance->setTotalCount($value);
        return $this;
    }

    /**
     * Sets total Amount field.
     *
     * @param float|null $value
     */
    public function totalAmount(?float $value): self
    {
        $this->instance->setTotalAmount($value);
        return $this;
    }

    /**
     * Sets summaries field.
     *
     * @param Summary1[]|null $value
     */
    public function summaries(?array $value): self
    {
        $this->instance->setSummaries($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Authorizations Summary Transactiondate Response object.
     */
    public function build(): AuthorizationsSummaryTransactiondateResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
