<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\CodeAndDescription;

/**
 * Builder for model CodeAndDescription
 *
 * @see CodeAndDescription
 */
class CodeAndDescriptionBuilder
{
    /**
     * @var CodeAndDescription
     */
    private $instance;

    private function __construct(CodeAndDescription $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Code And Description Builder object.
     */
    public static function init(): self
    {
        return new self(new CodeAndDescription());
    }

    /**
     * Sets code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets short Description field.
     *
     * @param string|null $value
     */
    public function shortDescription(?string $value): self
    {
        $this->instance->setShortDescription($value);
        return $this;
    }

    /**
     * Sets long Description field.
     *
     * @param string|null $value
     */
    public function longDescription(?string $value): self
    {
        $this->instance->setLongDescription($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Code And Description object.
     */
    public function build(): CodeAndDescription
    {
        return CoreHelper::clone($this->instance);
    }
}
