<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\DateRangeType;

/**
 * Builder for model DateRangeType
 *
 * @see DateRangeType
 */
class DateRangeTypeBuilder
{
    /**
     * @var DateRangeType
     */
    private $instance;

    private function __construct(DateRangeType $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Date Range Type Builder object.
     *
     * @param string $fromDate
     * @param string $toDate
     */
    public static function init(string $fromDate, string $toDate): self
    {
        return new self(new DateRangeType($fromDate, $toDate));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Date Range Type object.
     */
    public function build(): DateRangeType
    {
        return CoreHelper::clone($this->instance);
    }
}
