<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\EntityStoreResponse;

/**
 * Builder for model EntityStoreResponse
 *
 * @see EntityStoreResponse
 */
class EntityStoreResponseBuilder
{
    /**
     * @var EntityStoreResponse
     */
    private $instance;

    private function __construct(EntityStoreResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Entity Store Response Builder object.
     */
    public static function init(): self
    {
        return new self(new EntityStoreResponse());
    }

    /**
     * Sets chain Code field.
     *
     * @param string|null $value
     */
    public function chainCode(?string $value): self
    {
        $this->instance->setChainCode($value);
        return $this;
    }

    /**
     * Sets store Number field.
     *
     * @param string|null $value
     */
    public function storeNumber(?string $value): self
    {
        $this->instance->setStoreNumber($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Entity Store Response object.
     */
    public function build(): EntityStoreResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
