<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\EntityDivisionResponse;

/**
 * Builder for model EntityDivisionResponse
 *
 * @see EntityDivisionResponse
 */
class EntityDivisionResponseBuilder
{
    /**
     * @var EntityDivisionResponse
     */
    private $instance;

    private function __construct(EntityDivisionResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Entity Division Response Builder object.
     */
    public static function init(): self
    {
        return new self(new EntityDivisionResponse());
    }

    /**
     * Sets chain Code field.
     *
     * @param string|null $value
     */
    public function chainCode(?string $value): self
    {
        $this->instance->setChainCode($value);
        return $this;
    }

    /**
     * Sets division Number field.
     *
     * @param string|null $value
     */
    public function divisionNumber(?string $value): self
    {
        $this->instance->setDivisionNumber($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Entity Division Response object.
     */
    public function build(): EntityDivisionResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
