<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\Entity;

/**
 * Builder for model Entity
 *
 * @see Entity
 */
class EntityBuilder
{
    /**
     * @var Entity
     */
    private $instance;

    private function __construct(Entity $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Entity Builder object.
     */
    public static function init(): self
    {
        return new self(new Entity());
    }

    /**
     * Sets level field.
     *
     * @param string|null $value
     */
    public function level(?string $value): self
    {
        $this->instance->setLevel($value);
        return $this;
    }

    /**
     * Sets values field.
     *
     * @param string[]|null $value
     */
    public function values(?array $value): self
    {
        $this->instance->setValues($value);
        return $this;
    }

    /**
     * Sets chain Code field.
     *
     * @param string|null $value
     */
    public function chainCode(?string $value): self
    {
        $this->instance->setChainCode($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Entity object.
     */
    public function build(): Entity
    {
        return CoreHelper::clone($this->instance);
    }
}
