<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\Error;

/**
 * Builder for model Error
 *
 * @see Error
 */
class ErrorBuilder
{
    /**
     * @var Error
     */
    private $instance;

    private function __construct(Error $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Builder object.
     */
    public static function init(): self
    {
        return new self(new Error());
    }

    /**
     * Sets error Code field.
     *
     * @param string|null $value
     */
    public function errorCode(?string $value): self
    {
        $this->instance->setErrorCode($value);
        return $this;
    }

    /**
     * Sets error Message field.
     *
     * @param string|null $value
     */
    public function errorMessage(?string $value): self
    {
        $this->instance->setErrorMessage($value);
        return $this;
    }

    /**
     * Sets target field.
     *
     * @param string|null $value
     */
    public function target(?string $value): self
    {
        $this->instance->setTarget($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error object.
     */
    public function build(): Error
    {
        return CoreHelper::clone($this->instance);
    }
}
