<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\Error;
use ReportingAuthorizationSummaryApiLib\Models\ErrorResponse;

/**
 * Builder for model ErrorResponse
 *
 * @see ErrorResponse
 */
class ErrorResponseBuilder
{
    /**
     * @var ErrorResponse
     */
    private $instance;

    private function __construct(ErrorResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ErrorResponse());
    }

    /**
     * Sets errors field.
     *
     * @param Error[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Response object.
     */
    public function build(): ErrorResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
