<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\Pagination;

/**
 * Builder for model Pagination
 *
 * @see Pagination
 */
class PaginationBuilder
{
    /**
     * @var Pagination
     */
    private $instance;

    private function __construct(Pagination $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pagination Builder object.
     */
    public static function init(): self
    {
        return new self(new Pagination());
    }

    /**
     * Sets page Number field.
     *
     * @param int|null $value
     */
    public function pageNumber(?int $value): self
    {
        $this->instance->setPageNumber($value);
        return $this;
    }

    /**
     * Sets page Size field.
     *
     * @param int|null $value
     */
    public function pageSize(?int $value): self
    {
        $this->instance->setPageSize($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Pagination object.
     */
    public function build(): Pagination
    {
        return CoreHelper::clone($this->instance);
    }
}
