<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\SummaryDetailEntityEntity;

/**
 * Builder for model SummaryDetailEntityEntity
 *
 * @see SummaryDetailEntityEntity
 */
class SummaryDetailEntityEntityBuilder
{
    /**
     * @var SummaryDetailEntityEntity
     */
    private $instance;

    private function __construct(SummaryDetailEntityEntity $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Summary Detail Entity Entity Builder object.
     */
    public static function init(): self
    {
        return new self(new SummaryDetailEntityEntity());
    }

    /**
     * Sets merchant Id field.
     *
     * @param string|null $value
     */
    public function merchantId(?string $value): self
    {
        $this->instance->setMerchantId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Summary Detail Entity Entity object.
     */
    public function build(): SummaryDetailEntityEntity
    {
        return CoreHelper::clone($this->instance);
    }
}
