<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\SummaryDetailEntitySuperChain;

/**
 * Builder for model SummaryDetailEntitySuperChain
 *
 * @see SummaryDetailEntitySuperChain
 */
class SummaryDetailEntitySuperChainBuilder
{
    /**
     * @var SummaryDetailEntitySuperChain
     */
    private $instance;

    private function __construct(SummaryDetailEntitySuperChain $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Summary Detail Entity Super Chain Builder object.
     */
    public static function init(): self
    {
        return new self(new SummaryDetailEntitySuperChain());
    }

    /**
     * Sets super Chain Code field.
     *
     * @param string|null $value
     */
    public function superChainCode(?string $value): self
    {
        $this->instance->setSuperChainCode($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Summary Detail Entity Super Chain object.
     */
    public function build(): SummaryDetailEntitySuperChain
    {
        return CoreHelper::clone($this->instance);
    }
}
