<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\SummaryDetailEntityChain;

/**
 * Builder for model SummaryDetailEntityChain
 *
 * @see SummaryDetailEntityChain
 */
class SummaryDetailEntityChainBuilder
{
    /**
     * @var SummaryDetailEntityChain
     */
    private $instance;

    private function __construct(SummaryDetailEntityChain $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Summary Detail Entity Chain Builder object.
     */
    public static function init(): self
    {
        return new self(new SummaryDetailEntityChain());
    }

    /**
     * Sets chain Code field.
     *
     * @param string|null $value
     */
    public function chainCode(?string $value): self
    {
        $this->instance->setChainCode($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Summary Detail Entity Chain object.
     */
    public function build(): SummaryDetailEntityChain
    {
        return CoreHelper::clone($this->instance);
    }
}
