<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ReportingAuthorizationSummaryApiLib\Models\CodeAndDescription;
use ReportingAuthorizationSummaryApiLib\Models\Summary;

/**
 * Builder for model Summary
 *
 * @see Summary
 */
class SummaryBuilder
{
    /**
     * @var Summary
     */
    private $instance;

    private function __construct(Summary $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Summary Builder object.
     */
    public static function init(): self
    {
        return new self(new Summary());
    }

    /**
     * Sets approved Count field.
     *
     * @param int|null $value
     */
    public function approvedCount(?int $value): self
    {
        $this->instance->setApprovedCount($value);
        return $this;
    }

    /**
     * Sets approved Amount field.
     *
     * @param float|null $value
     */
    public function approvedAmount(?float $value): self
    {
        $this->instance->setApprovedAmount($value);
        return $this;
    }

    /**
     * Sets declined Count field.
     *
     * @param int|null $value
     */
    public function declinedCount(?int $value): self
    {
        $this->instance->setDeclinedCount($value);
        return $this;
    }

    /**
     * Sets declined Amount field.
     *
     * @param float|null $value
     */
    public function declinedAmount(?float $value): self
    {
        $this->instance->setDeclinedAmount($value);
        return $this;
    }

    /**
     * Sets approved Count Percent field.
     *
     * @param float|null $value
     */
    public function approvedCountPercent(?float $value): self
    {
        $this->instance->setApprovedCountPercent($value);
        return $this;
    }

    /**
     * Sets approved Amount Percent field.
     *
     * @param float|null $value
     */
    public function approvedAmountPercent(?float $value): self
    {
        $this->instance->setApprovedAmountPercent($value);
        return $this;
    }

    /**
     * Sets declined Count Percent field.
     *
     * @param float|null $value
     */
    public function declinedCountPercent(?float $value): self
    {
        $this->instance->setDeclinedCountPercent($value);
        return $this;
    }

    /**
     * Sets declined Amount Percent field.
     *
     * @param float|null $value
     */
    public function declinedAmountPercent(?float $value): self
    {
        $this->instance->setDeclinedAmountPercent($value);
        return $this;
    }

    /**
     * Sets card Type field.
     *
     * @param string|null $value
     */
    public function cardType(?string $value): self
    {
        $this->instance->setCardType($value);
        return $this;
    }

    /**
     * Sets card Network field.
     *
     * @param CodeAndDescription|null $value
     */
    public function cardNetwork(?CodeAndDescription $value): self
    {
        $this->instance->setCardNetwork($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Summary object.
     */
    public function build(): Summary
    {
        return CoreHelper::clone($this->instance);
    }
}
