<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Exceptions;

use ReportingAuthorizationSummaryApiLib\ApiHelper;

class AuthorizationsSummaryCardnetwork0ErrorException extends ApiException
{
    /**
     * @var \ReportingAuthorizationSummaryApiLib\Models\Error[]|null
     */
    private $errors;

    /**
     * Returns Errors.
     * The list of errors.
     *
     * @return \ReportingAuthorizationSummaryApiLib\Models\Error[]|null
     */
    public function getErrors(): ?array
    {
        return $this->errors;
    }

    /**
     * Sets Errors.
     * The list of errors.
     *
     * @maps errors
     *
     * @param \ReportingAuthorizationSummaryApiLib\Models\Error[]|null $errors
     */
    public function setErrors(?array $errors): void
    {
        $this->errors = $errors;
    }

    /**
     * Converts the AuthorizationsSummaryCardnetwork0ErrorException object to a human-readable string
     * representation.
     *
     * @return string The string representation of the AuthorizationsSummaryCardnetwork0ErrorException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AuthorizationsSummaryCardnetwork0ErrorException',
            ['errors' => $this->errors, 'additionalProperties' => $this->additionalProperties],
            parent::__toString()
        );
    }

    protected $propertyNames = ['errors'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }
}
