<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use ReportingAuthorizationSummaryApiLib\ApiHelper;
use stdClass;

class AuthTransactionsSummaryRequestByMerchant implements \JsonSerializable
{
    /**
     * @var Pagination|null
     */
    private $pagination;

    /**
     * @var Entity
     */
    private $hierarchy;

    /**
     * @var string|null
     */
    private $cardType;

    /**
     * @var string[]|null
     */
    private $cardNetworks;

    /**
     * @var DateRange
     */
    private $dateRange;

    /**
     * @param Entity $hierarchy
     * @param DateRange $dateRange
     */
    public function __construct(Entity $hierarchy, DateRange $dateRange)
    {
        $this->hierarchy = $hierarchy;
        $this->dateRange = $dateRange;
    }

    /**
     * Returns Pagination.
     */
    public function getPagination(): ?Pagination
    {
        return $this->pagination;
    }

    /**
     * Sets Pagination.
     *
     * @maps pagination
     */
    public function setPagination(?Pagination $pagination): void
    {
        $this->pagination = $pagination;
    }

    /**
     * Returns Hierarchy.
     */
    public function getHierarchy(): Entity
    {
        return $this->hierarchy;
    }

    /**
     * Sets Hierarchy.
     *
     * @required
     * @maps hierarchy
     */
    public function setHierarchy(Entity $hierarchy): void
    {
        $this->hierarchy = $hierarchy;
    }

    /**
     * Returns Card Type.
     * The category or classification of a payment card based on the issuing network. Default is Credit.
     */
    public function getCardType(): ?string
    {
        return $this->cardType;
    }

    /**
     * Sets Card Type.
     * The category or classification of a payment card based on the issuing network. Default is Credit.
     *
     * @maps cardType
     */
    public function setCardType(?string $cardType): void
    {
        $this->cardType = $cardType;
    }

    /**
     * Returns Card Networks.
     * The network the card is associated with that facilitates the payment. <br>Default is All Card
     * Networks.
     *
     * @return string[]|null
     */
    public function getCardNetworks(): ?array
    {
        return $this->cardNetworks;
    }

    /**
     * Sets Card Networks.
     * The network the card is associated with that facilitates the payment. <br>Default is All Card
     * Networks.
     *
     * @maps cardNetworks
     * @factory \ReportingAuthorizationSummaryApiLib\Models\CardNetworkType::checkValue
     *
     * @param string[]|null $cardNetworks
     */
    public function setCardNetworks(?array $cardNetworks): void
    {
        $this->cardNetworks = $cardNetworks;
    }

    /**
     * Returns Date Range.
     */
    public function getDateRange(): DateRange
    {
        return $this->dateRange;
    }

    /**
     * Sets Date Range.
     *
     * @required
     * @maps dateRange
     */
    public function setDateRange(DateRange $dateRange): void
    {
        $this->dateRange = $dateRange;
    }

    /**
     * Converts the AuthTransactionsSummaryRequestByMerchant object to a human-readable string
     * representation.
     *
     * @return string The string representation of the AuthTransactionsSummaryRequestByMerchant object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AuthTransactionsSummaryRequestByMerchant',
            [
                'pagination' => $this->pagination,
                'hierarchy' => $this->hierarchy,
                'cardType' => $this->cardType,
                'cardNetworks' => $this->cardNetworks,
                'dateRange' => $this->dateRange,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['pagination', 'hierarchy', 'cardType', 'cardNetworks', 'dateRange'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->pagination)) {
            $json['pagination']   = $this->pagination;
        }
        $json['hierarchy']        = $this->hierarchy;
        if (isset($this->cardType)) {
            $json['cardType']     = $this->cardType;
        }
        if (isset($this->cardNetworks)) {
            $json['cardNetworks'] = CardNetworkType::checkValue($this->cardNetworks);
        }
        $json['dateRange']        = $this->dateRange;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
