<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class CardNetworkType
{
    public const BILL_ME_LATER = 'BILL_ME_LATER';

    public const VISA = 'VISA';

    public const MASTERCARD = 'MASTERCARD';

    public const DISCOVER = 'DISCOVER';

    public const AMEX = 'AMEX';

    public const DINERS = 'DINERS';

    public const WRIGHT_EXPRESS = 'WRIGHT_EXPRESS';

    public const VOYAGER = 'VOYAGER';

    public const PRIVATE_LABEL = 'PRIVATE_LABEL';

    public const JCB = 'JCB';

    private const _ALL_VALUES = [
        self::BILL_ME_LATER,
        self::VISA,
        self::MASTERCARD,
        self::DISCOVER,
        self::AMEX,
        self::DINERS,
        self::WRIGHT_EXPRESS,
        self::VOYAGER,
        self::PRIVATE_LABEL,
        self::JCB
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for CardNetworkType.");
    }
}
