<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use ReportingAuthorizationSummaryApiLib\ApiHelper;
use stdClass;

class CodeAndDescription implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $code;

    /**
     * @var string|null
     */
    private $shortDescription;

    /**
     * @var string|null
     */
    private $longDescription;

    /**
     * Returns Code.
     * The code.
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     * The code.
     *
     * @maps code
     */
    public function setCode(?string $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Short Description.
     * Short description.
     */
    public function getShortDescription(): ?string
    {
        return $this->shortDescription;
    }

    /**
     * Sets Short Description.
     * Short description.
     *
     * @maps shortDescription
     */
    public function setShortDescription(?string $shortDescription): void
    {
        $this->shortDescription = $shortDescription;
    }

    /**
     * Returns Long Description.
     * Long description.
     */
    public function getLongDescription(): ?string
    {
        return $this->longDescription;
    }

    /**
     * Sets Long Description.
     * Long description.
     *
     * @maps longDescription
     */
    public function setLongDescription(?string $longDescription): void
    {
        $this->longDescription = $longDescription;
    }

    /**
     * Converts the CodeAndDescription object to a human-readable string representation.
     *
     * @return string The string representation of the CodeAndDescription object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CodeAndDescription',
            [
                'code' => $this->code,
                'shortDescription' => $this->shortDescription,
                'longDescription' => $this->longDescription,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['code', 'shortDescription', 'longDescription'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->code)) {
            $json['code']             = $this->code;
        }
        if (isset($this->shortDescription)) {
            $json['shortDescription'] = $this->shortDescription;
        }
        if (isset($this->longDescription)) {
            $json['longDescription']  = $this->longDescription;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
