<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use ReportingAuthorizationSummaryApiLib\ApiHelper;
use stdClass;

class CommonSummaryResponses implements \JsonSerializable
{
    /**
     * @var PaginationResponse|null
     */
    private $pagination;

    /**
     * @var int|null
     */
    private $totalApprovedCount;

    /**
     * @var float|null
     */
    private $totalApprovedAmount;

    /**
     * @var int|null
     */
    private $totalDeclinedCount;

    /**
     * @var float|null
     */
    private $totalDeclinedAmount;

    /**
     * @var float|null
     */
    private $totalApprovedCountPercent;

    /**
     * @var float|null
     */
    private $totalApprovedAmountPercent;

    /**
     * @var float|null
     */
    private $totalDeclinedCountPercent;

    /**
     * @var float|null
     */
    private $totalDeclinedAmountPercent;

    /**
     * @var int|null
     */
    private $totalCount;

    /**
     * @var float|null
     */
    private $totalAmount;

    /**
     * Returns Pagination.
     */
    public function getPagination(): ?PaginationResponse
    {
        return $this->pagination;
    }

    /**
     * Sets Pagination.
     *
     * @maps pagination
     */
    public function setPagination(?PaginationResponse $pagination): void
    {
        $this->pagination = $pagination;
    }

    /**
     * Returns Total Approved Count.
     * Count of the approved transactions.
     */
    public function getTotalApprovedCount(): ?int
    {
        return $this->totalApprovedCount;
    }

    /**
     * Sets Total Approved Count.
     * Count of the approved transactions.
     *
     * @maps totalApprovedCount
     */
    public function setTotalApprovedCount(?int $totalApprovedCount): void
    {
        $this->totalApprovedCount = $totalApprovedCount;
    }

    /**
     * Returns Total Approved Amount.
     * Sum of the amount of approved transactions.
     */
    public function getTotalApprovedAmount(): ?float
    {
        return $this->totalApprovedAmount;
    }

    /**
     * Sets Total Approved Amount.
     * Sum of the amount of approved transactions.
     *
     * @maps totalApprovedAmount
     */
    public function setTotalApprovedAmount(?float $totalApprovedAmount): void
    {
        $this->totalApprovedAmount = $totalApprovedAmount;
    }

    /**
     * Returns Total Declined Count.
     * Count of the declined transactions.
     */
    public function getTotalDeclinedCount(): ?int
    {
        return $this->totalDeclinedCount;
    }

    /**
     * Sets Total Declined Count.
     * Count of the declined transactions.
     *
     * @maps totalDeclinedCount
     */
    public function setTotalDeclinedCount(?int $totalDeclinedCount): void
    {
        $this->totalDeclinedCount = $totalDeclinedCount;
    }

    /**
     * Returns Total Declined Amount.
     * Sum of the amount of declined transactions.
     */
    public function getTotalDeclinedAmount(): ?float
    {
        return $this->totalDeclinedAmount;
    }

    /**
     * Sets Total Declined Amount.
     * Sum of the amount of declined transactions.
     *
     * @maps totalDeclinedAmount
     */
    public function setTotalDeclinedAmount(?float $totalDeclinedAmount): void
    {
        $this->totalDeclinedAmount = $totalDeclinedAmount;
    }

    /**
     * Returns Total Approved Count Percent.
     * Ratio of the count of approved transactions to the count of total transctions.
     */
    public function getTotalApprovedCountPercent(): ?float
    {
        return $this->totalApprovedCountPercent;
    }

    /**
     * Sets Total Approved Count Percent.
     * Ratio of the count of approved transactions to the count of total transctions.
     *
     * @maps totalApprovedCountPercent
     */
    public function setTotalApprovedCountPercent(?float $totalApprovedCountPercent): void
    {
        $this->totalApprovedCountPercent = $totalApprovedCountPercent;
    }

    /**
     * Returns Total Approved Amount Percent.
     * Ratio of the sum of the amount of the approved transactions to the sum of amount of total
     * transctions.
     */
    public function getTotalApprovedAmountPercent(): ?float
    {
        return $this->totalApprovedAmountPercent;
    }

    /**
     * Sets Total Approved Amount Percent.
     * Ratio of the sum of the amount of the approved transactions to the sum of amount of total
     * transctions.
     *
     * @maps totalApprovedAmountPercent
     */
    public function setTotalApprovedAmountPercent(?float $totalApprovedAmountPercent): void
    {
        $this->totalApprovedAmountPercent = $totalApprovedAmountPercent;
    }

    /**
     * Returns Total Declined Count Percent.
     * Ratio of the count of the declined transactions to the count of total transctions.
     */
    public function getTotalDeclinedCountPercent(): ?float
    {
        return $this->totalDeclinedCountPercent;
    }

    /**
     * Sets Total Declined Count Percent.
     * Ratio of the count of the declined transactions to the count of total transctions.
     *
     * @maps totalDeclinedCountPercent
     */
    public function setTotalDeclinedCountPercent(?float $totalDeclinedCountPercent): void
    {
        $this->totalDeclinedCountPercent = $totalDeclinedCountPercent;
    }

    /**
     * Returns Total Declined Amount Percent.
     * Ratio of the sum of the amount of the declined transactions to the sum of the amount of total
     * transctions.
     */
    public function getTotalDeclinedAmountPercent(): ?float
    {
        return $this->totalDeclinedAmountPercent;
    }

    /**
     * Sets Total Declined Amount Percent.
     * Ratio of the sum of the amount of the declined transactions to the sum of the amount of total
     * transctions.
     *
     * @maps totalDeclinedAmountPercent
     */
    public function setTotalDeclinedAmountPercent(?float $totalDeclinedAmountPercent): void
    {
        $this->totalDeclinedAmountPercent = $totalDeclinedAmountPercent;
    }

    /**
     * Returns Total Count.
     * Sum of the count of the approved transactions and the count of the declined transactions.
     */
    public function getTotalCount(): ?int
    {
        return $this->totalCount;
    }

    /**
     * Sets Total Count.
     * Sum of the count of the approved transactions and the count of the declined transactions.
     *
     * @maps totalCount
     */
    public function setTotalCount(?int $totalCount): void
    {
        $this->totalCount = $totalCount;
    }

    /**
     * Returns Total Amount.
     * Sum of the amount of approved transactions and the amount of the declined transactions.
     */
    public function getTotalAmount(): ?float
    {
        return $this->totalAmount;
    }

    /**
     * Sets Total Amount.
     * Sum of the amount of approved transactions and the amount of the declined transactions.
     *
     * @maps totalAmount
     */
    public function setTotalAmount(?float $totalAmount): void
    {
        $this->totalAmount = $totalAmount;
    }

    /**
     * Converts the CommonSummaryResponses object to a human-readable string representation.
     *
     * @return string The string representation of the CommonSummaryResponses object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CommonSummaryResponses',
            [
                'pagination' => $this->pagination,
                'totalApprovedCount' => $this->totalApprovedCount,
                'totalApprovedAmount' => $this->totalApprovedAmount,
                'totalDeclinedCount' => $this->totalDeclinedCount,
                'totalDeclinedAmount' => $this->totalDeclinedAmount,
                'totalApprovedCountPercent' => $this->totalApprovedCountPercent,
                'totalApprovedAmountPercent' => $this->totalApprovedAmountPercent,
                'totalDeclinedCountPercent' => $this->totalDeclinedCountPercent,
                'totalDeclinedAmountPercent' => $this->totalDeclinedAmountPercent,
                'totalCount' => $this->totalCount,
                'totalAmount' => $this->totalAmount,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'pagination',
        'totalApprovedCount',
        'totalApprovedAmount',
        'totalDeclinedCount',
        'totalDeclinedAmount',
        'totalApprovedCountPercent',
        'totalApprovedAmountPercent',
        'totalDeclinedCountPercent',
        'totalDeclinedAmountPercent',
        'totalCount',
        'totalAmount'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->pagination)) {
            $json['pagination']                 = $this->pagination;
        }
        if (isset($this->totalApprovedCount)) {
            $json['totalApprovedCount']         = $this->totalApprovedCount;
        }
        if (isset($this->totalApprovedAmount)) {
            $json['totalApprovedAmount']        = $this->totalApprovedAmount;
        }
        if (isset($this->totalDeclinedCount)) {
            $json['totalDeclinedCount']         = $this->totalDeclinedCount;
        }
        if (isset($this->totalDeclinedAmount)) {
            $json['totalDeclinedAmount']        = $this->totalDeclinedAmount;
        }
        if (isset($this->totalApprovedCountPercent)) {
            $json['totalApprovedCountPercent']  = $this->totalApprovedCountPercent;
        }
        if (isset($this->totalApprovedAmountPercent)) {
            $json['totalApprovedAmountPercent'] = $this->totalApprovedAmountPercent;
        }
        if (isset($this->totalDeclinedCountPercent)) {
            $json['totalDeclinedCountPercent']  = $this->totalDeclinedCountPercent;
        }
        if (isset($this->totalDeclinedAmountPercent)) {
            $json['totalDeclinedAmountPercent'] = $this->totalDeclinedAmountPercent;
        }
        if (isset($this->totalCount)) {
            $json['totalCount']                 = $this->totalCount;
        }
        if (isset($this->totalAmount)) {
            $json['totalAmount']                = $this->totalAmount;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
