<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use ReportingAuthorizationSummaryApiLib\ApiHelper;
use stdClass;

/**
 * All dates including and between a specified start and end date. <br> Date range for different
 * hierarchy level:<br><br>07 Days:<br>Independent Sales Organizationn(SO),Independent Sales
 * Affiliate(SA), National(NL), Partner(PT), SuperChain(SC)<br><br>45 days:<br>Chain(CH), Merchant(MT).
 */
class DateRangeType implements \JsonSerializable
{
    /**
     * @var string
     */
    private $fromDate;

    /**
     * @var string
     */
    private $toDate;

    /**
     * @param string $fromDate
     * @param string $toDate
     */
    public function __construct(string $fromDate, string $toDate)
    {
        $this->fromDate = $fromDate;
        $this->toDate = $toDate;
    }

    /**
     * Returns From Date.
     * The starting date of the specified time period.
     */
    public function getFromDate(): string
    {
        return $this->fromDate;
    }

    /**
     * Sets From Date.
     * The starting date of the specified time period.
     *
     * @required
     * @maps fromDate
     */
    public function setFromDate(string $fromDate): void
    {
        $this->fromDate = $fromDate;
    }

    /**
     * Returns To Date.
     * The end date of the specified time period.
     */
    public function getToDate(): string
    {
        return $this->toDate;
    }

    /**
     * Sets To Date.
     * The end date of the specified time period.
     *
     * @required
     * @maps toDate
     */
    public function setToDate(string $toDate): void
    {
        $this->toDate = $toDate;
    }

    /**
     * Converts the DateRangeType object to a human-readable string representation.
     *
     * @return string The string representation of the DateRangeType object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'DateRangeType',
            [
                'fromDate' => $this->fromDate,
                'toDate' => $this->toDate,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['fromDate', 'toDate'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['fromDate'] = $this->fromDate;
        $json['toDate']   = $this->toDate;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
