<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use ReportingAuthorizationSummaryApiLib\ApiHelper;
use stdClass;

class EntityStoreResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $chainCode;

    /**
     * @var string|null
     */
    private $storeNumber;

    /**
     * Returns Chain Code.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related roll-up
     * values under a common identifier for settlement, billing, and reporting. Chain Code is the primary
     * identifier for merchants boarded in a MDB (Merchant Database) system.
     */
    public function getChainCode(): ?string
    {
        return $this->chainCode;
    }

    /**
     * Sets Chain Code.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related roll-up
     * values under a common identifier for settlement, billing, and reporting. Chain Code is the primary
     * identifier for merchants boarded in a MDB (Merchant Database) system.
     *
     * @maps chainCode
     */
    public function setChainCode(?string $chainCode): void
    {
        $this->chainCode = $chainCode;
    }

    /**
     * Returns Store Number.
     * The lowest roll-up level in the hierarchy system, grouping multiple merchant account numbers (MIDs)
     * used in a single merchant location assigned to different terminals and/or business lines (MCCs). A
     * Store Number is nine digits and unique to a particular Chain, meaning the same Store Number can
     * exist for a Store under a different Divison/Chain, but not duplicates under the same Divison/Chain.
     * <br> Supports entities Chain, National.
     */
    public function getStoreNumber(): ?string
    {
        return $this->storeNumber;
    }

    /**
     * Sets Store Number.
     * The lowest roll-up level in the hierarchy system, grouping multiple merchant account numbers (MIDs)
     * used in a single merchant location assigned to different terminals and/or business lines (MCCs). A
     * Store Number is nine digits and unique to a particular Chain, meaning the same Store Number can
     * exist for a Store under a different Divison/Chain, but not duplicates under the same Divison/Chain.
     * <br> Supports entities Chain, National.
     *
     * @maps storeNumber
     */
    public function setStoreNumber(?string $storeNumber): void
    {
        $this->storeNumber = $storeNumber;
    }

    /**
     * Converts the EntityStoreResponse object to a human-readable string representation.
     *
     * @return string The string representation of the EntityStoreResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EntityStoreResponse',
            [
                'chainCode' => $this->chainCode,
                'storeNumber' => $this->storeNumber,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['chainCode', 'storeNumber'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->chainCode)) {
            $json['chainCode']   = $this->chainCode;
        }
        if (isset($this->storeNumber)) {
            $json['storeNumber'] = $this->storeNumber;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
