<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use ReportingAuthorizationSummaryApiLib\ApiHelper;
use stdClass;

class EntityDivisionResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $chainCode;

    /**
     * @var string|null
     */
    private $divisionNumber;

    /**
     * Returns Chain Code.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related roll-up
     * values under a common identifier for settlement, billing, and reporting. Chain Code is the primary
     * identifier for merchants boarded in a MDB (Merchant Database) system.
     */
    public function getChainCode(): ?string
    {
        return $this->chainCode;
    }

    /**
     * Sets Chain Code.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related roll-up
     * values under a common identifier for settlement, billing, and reporting. Chain Code is the primary
     * identifier for merchants boarded in a MDB (Merchant Database) system.
     *
     * @maps chainCode
     */
    public function setChainCode(?string $chainCode): void
    {
        $this->chainCode = $chainCode;
    }

    /**
     * Returns Division Number.
     * The hierarchy level that enables merchants to roll-up child entities for Stores/Locations into
     * different groups under a Chain. It is an optional hierarchy level, but if created, is required for
     * all child entities under the Division Number which is unique to that particular Chain. <br> Supports
     * entities Chain, National.
     */
    public function getDivisionNumber(): ?string
    {
        return $this->divisionNumber;
    }

    /**
     * Sets Division Number.
     * The hierarchy level that enables merchants to roll-up child entities for Stores/Locations into
     * different groups under a Chain. It is an optional hierarchy level, but if created, is required for
     * all child entities under the Division Number which is unique to that particular Chain. <br> Supports
     * entities Chain, National.
     *
     * @maps divisionNumber
     */
    public function setDivisionNumber(?string $divisionNumber): void
    {
        $this->divisionNumber = $divisionNumber;
    }

    /**
     * Converts the EntityDivisionResponse object to a human-readable string representation.
     *
     * @return string The string representation of the EntityDivisionResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EntityDivisionResponse',
            [
                'chainCode' => $this->chainCode,
                'divisionNumber' => $this->divisionNumber,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['chainCode', 'divisionNumber'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->chainCode)) {
            $json['chainCode']      = $this->chainCode;
        }
        if (isset($this->divisionNumber)) {
            $json['divisionNumber'] = $this->divisionNumber;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
