<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use ReportingAuthorizationSummaryApiLib\ApiHelper;
use stdClass;

class Entity implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $level;

    /**
     * @var string[]|null
     */
    private $values;

    /**
     * @var string|null
     */
    private $chainCode;

    /**
     * Returns Level.
     */
    public function getLevel(): ?string
    {
        return $this->level;
    }

    /**
     * Sets Level.
     *
     * @maps level
     * @factory \ReportingAuthorizationSummaryApiLib\Models\Level::checkValue
     */
    public function setLevel(?string $level): void
    {
        $this->level = $level;
    }

    /**
     * Returns Values.
     * Refers to hierarchy id. Accepts a list of ids.
     *
     * @return string[]|null
     */
    public function getValues(): ?array
    {
        return $this->values;
    }

    /**
     * Sets Values.
     * Refers to hierarchy id. Accepts a list of ids.
     *
     * @maps values
     *
     * @param string[]|null $values
     */
    public function setValues(?array $values): void
    {
        $this->values = $values;
    }

    /**
     * Returns Chain Code.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related roll-up
     * values under a common identifier for settlement, billing, and reporting. Chain Code is the primary
     * identifier for merchants boarded in a MDB (Merchant Database) system. <br> Chain code is mandatory
     * when the hierarchy level selected is Store or Division.
     */
    public function getChainCode(): ?string
    {
        return $this->chainCode;
    }

    /**
     * Sets Chain Code.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related roll-up
     * values under a common identifier for settlement, billing, and reporting. Chain Code is the primary
     * identifier for merchants boarded in a MDB (Merchant Database) system. <br> Chain code is mandatory
     * when the hierarchy level selected is Store or Division.
     *
     * @maps chainCode
     */
    public function setChainCode(?string $chainCode): void
    {
        $this->chainCode = $chainCode;
    }

    /**
     * Converts the Entity object to a human-readable string representation.
     *
     * @return string The string representation of the Entity object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Entity',
            [
                'level' => $this->level,
                'values' => $this->values,
                'chainCode' => $this->chainCode,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['level', 'values', 'chainCode'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->level)) {
            $json['level']     = Level::checkValue($this->level);
        }
        if (isset($this->values)) {
            $json['values']    = $this->values;
        }
        if (isset($this->chainCode)) {
            $json['chainCode'] = $this->chainCode;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
