<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Supports entities such as Independent Sales Organization and Independent Sales Channel with a limit
 * of one entity, <br>National, SuperChain, Partner with a maximum limit of 10 entities, <br>Chain,
 * Division, Store, and Merchant with a maximum limit of 2000 entities.
 */
class Level
{
    public const MERCHANT = 'MERCHANT';

    public const STORE = 'STORE';

    public const DIVISION = 'DIVISION';

    public const CHAIN = 'CHAIN';

    public const PARTNER = 'PARTNER';

    public const SUPERCHAIN = 'SUPERCHAIN';

    public const NATIONAL = 'NATIONAL';

    public const INDEPENDENT_SALES_CHANNEL = 'INDEPENDENT_SALES_CHANNEL';

    public const INDEPENDENT_SALES_ORGANIZATION = 'INDEPENDENT_SALES_ORGANIZATION';

    private const _ALL_VALUES = [
        self::MERCHANT,
        self::STORE,
        self::DIVISION,
        self::CHAIN,
        self::PARTNER,
        self::SUPERCHAIN,
        self::NATIONAL,
        self::INDEPENDENT_SALES_CHANNEL,
        self::INDEPENDENT_SALES_ORGANIZATION
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Level.");
    }
}
