<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use ReportingAuthorizationSummaryApiLib\ApiHelper;
use stdClass;

class Pagination implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $pageNumber = 1;

    /**
     * @var int|null
     */
    private $pageSize = 25;

    /**
     * Returns Page Number.
     * The number of the specific page you want to retrieve. <br>Default is page number 01.
     */
    public function getPageNumber(): ?int
    {
        return $this->pageNumber;
    }

    /**
     * Sets Page Number.
     * The number of the specific page you want to retrieve. <br>Default is page number 01.
     *
     * @maps pageNumber
     */
    public function setPageNumber(?int $pageNumber): void
    {
        $this->pageNumber = $pageNumber;
    }

    /**
     * Returns Page Size.
     * The number of records that you would want to retrieve per page. <br>Default is 25 items per page.
     */
    public function getPageSize(): ?int
    {
        return $this->pageSize;
    }

    /**
     * Sets Page Size.
     * The number of records that you would want to retrieve per page. <br>Default is 25 items per page.
     *
     * @maps pageSize
     */
    public function setPageSize(?int $pageSize): void
    {
        $this->pageSize = $pageSize;
    }

    /**
     * Converts the Pagination object to a human-readable string representation.
     *
     * @return string The string representation of the Pagination object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Pagination',
            [
                'pageNumber' => $this->pageNumber,
                'pageSize' => $this->pageSize,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['pageNumber', 'pageSize'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->pageNumber)) {
            $json['pageNumber'] = $this->pageNumber;
        }
        if (isset($this->pageSize)) {
            $json['pageSize']   = $this->pageSize;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
