<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use ReportingAuthorizationSummaryApiLib\ApiHelper;
use stdClass;

class PaginationResponse implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $pageNumber;

    /**
     * @var int|null
     */
    private $pageSize;

    /**
     * @var int|null
     */
    private $totalRowCount;

    /**
     * @var int|null
     */
    private $totalReturnedCount;

    /**
     * Returns Page Number.
     * The number of the specific page you want to retrieve.
     */
    public function getPageNumber(): ?int
    {
        return $this->pageNumber;
    }

    /**
     * Sets Page Number.
     * The number of the specific page you want to retrieve.
     *
     * @maps pageNumber
     */
    public function setPageNumber(?int $pageNumber): void
    {
        $this->pageNumber = $pageNumber;
    }

    /**
     * Returns Page Size.
     * The number of records that you would want to retrieve per page.
     */
    public function getPageSize(): ?int
    {
        return $this->pageSize;
    }

    /**
     * Sets Page Size.
     * The number of records that you would want to retrieve per page.
     *
     * @maps pageSize
     */
    public function setPageSize(?int $pageSize): void
    {
        $this->pageSize = $pageSize;
    }

    /**
     * Returns Total Row Count.
     * The total number of result rows returned.
     */
    public function getTotalRowCount(): ?int
    {
        return $this->totalRowCount;
    }

    /**
     * Sets Total Row Count.
     * The total number of result rows returned.
     *
     * @maps totalRowCount
     */
    public function setTotalRowCount(?int $totalRowCount): void
    {
        $this->totalRowCount = $totalRowCount;
    }

    /**
     * Returns Total Returned Count.
     * The total number of records returned.
     */
    public function getTotalReturnedCount(): ?int
    {
        return $this->totalReturnedCount;
    }

    /**
     * Sets Total Returned Count.
     * The total number of records returned.
     *
     * @maps totalReturnedCount
     */
    public function setTotalReturnedCount(?int $totalReturnedCount): void
    {
        $this->totalReturnedCount = $totalReturnedCount;
    }

    /**
     * Converts the PaginationResponse object to a human-readable string representation.
     *
     * @return string The string representation of the PaginationResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaginationResponse',
            [
                'pageNumber' => $this->pageNumber,
                'pageSize' => $this->pageSize,
                'totalRowCount' => $this->totalRowCount,
                'totalReturnedCount' => $this->totalReturnedCount,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['pageNumber', 'pageSize', 'totalRowCount', 'totalReturnedCount'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->pageNumber)) {
            $json['pageNumber']         = $this->pageNumber;
        }
        if (isset($this->pageSize)) {
            $json['pageSize']           = $this->pageSize;
        }
        if (isset($this->totalRowCount)) {
            $json['totalRowCount']      = $this->totalRowCount;
        }
        if (isset($this->totalReturnedCount)) {
            $json['totalReturnedCount'] = $this->totalReturnedCount;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
