<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use ReportingAuthorizationSummaryApiLib\ApiHelper;
use stdClass;

class Summary2 implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $approvedCount;

    /**
     * @var float|null
     */
    private $approvedAmount;

    /**
     * @var int|null
     */
    private $declinedCount;

    /**
     * @var float|null
     */
    private $declinedAmount;

    /**
     * @var float|null
     */
    private $approvedCountPercent;

    /**
     * @var float|null
     */
    private $approvedAmountPercent;

    /**
     * @var float|null
     */
    private $declinedCountPercent;

    /**
     * @var float|null
     */
    private $declinedAmountPercent;

    /**
     * @var string|null
     */
    private $chainCode;

    /**
     * @var string|null
     */
    private $storeNumber;

    /**
     * Returns Approved Count.
     * Count of the approved transactions.
     */
    public function getApprovedCount(): ?int
    {
        return $this->approvedCount;
    }

    /**
     * Sets Approved Count.
     * Count of the approved transactions.
     *
     * @maps approvedCount
     */
    public function setApprovedCount(?int $approvedCount): void
    {
        $this->approvedCount = $approvedCount;
    }

    /**
     * Returns Approved Amount.
     * Sum of the amount of approved transactions.
     */
    public function getApprovedAmount(): ?float
    {
        return $this->approvedAmount;
    }

    /**
     * Sets Approved Amount.
     * Sum of the amount of approved transactions.
     *
     * @maps approvedAmount
     */
    public function setApprovedAmount(?float $approvedAmount): void
    {
        $this->approvedAmount = $approvedAmount;
    }

    /**
     * Returns Declined Count.
     * Count of the declined transactions.
     */
    public function getDeclinedCount(): ?int
    {
        return $this->declinedCount;
    }

    /**
     * Sets Declined Count.
     * Count of the declined transactions.
     *
     * @maps declinedCount
     */
    public function setDeclinedCount(?int $declinedCount): void
    {
        $this->declinedCount = $declinedCount;
    }

    /**
     * Returns Declined Amount.
     * Sum of the amount of the declined transactions.
     */
    public function getDeclinedAmount(): ?float
    {
        return $this->declinedAmount;
    }

    /**
     * Sets Declined Amount.
     * Sum of the amount of the declined transactions.
     *
     * @maps declinedAmount
     */
    public function setDeclinedAmount(?float $declinedAmount): void
    {
        $this->declinedAmount = $declinedAmount;
    }

    /**
     * Returns Approved Count Percent.
     * Ratio of the count of the approved transactions to the count of total transctions.
     */
    public function getApprovedCountPercent(): ?float
    {
        return $this->approvedCountPercent;
    }

    /**
     * Sets Approved Count Percent.
     * Ratio of the count of the approved transactions to the count of total transctions.
     *
     * @maps approvedCountPercent
     */
    public function setApprovedCountPercent(?float $approvedCountPercent): void
    {
        $this->approvedCountPercent = $approvedCountPercent;
    }

    /**
     * Returns Approved Amount Percent.
     * Ratio of the sum of the amount of approved transactions to the sum of the amount of total
     * transctions.
     */
    public function getApprovedAmountPercent(): ?float
    {
        return $this->approvedAmountPercent;
    }

    /**
     * Sets Approved Amount Percent.
     * Ratio of the sum of the amount of approved transactions to the sum of the amount of total
     * transctions.
     *
     * @maps approvedAmountPercent
     */
    public function setApprovedAmountPercent(?float $approvedAmountPercent): void
    {
        $this->approvedAmountPercent = $approvedAmountPercent;
    }

    /**
     * Returns Declined Count Percent.
     * Ratio of the count of the declined transactions to the count of total transctions.
     */
    public function getDeclinedCountPercent(): ?float
    {
        return $this->declinedCountPercent;
    }

    /**
     * Sets Declined Count Percent.
     * Ratio of the count of the declined transactions to the count of total transctions.
     *
     * @maps declinedCountPercent
     */
    public function setDeclinedCountPercent(?float $declinedCountPercent): void
    {
        $this->declinedCountPercent = $declinedCountPercent;
    }

    /**
     * Returns Declined Amount Percent.
     * Ratio of the sum of the amount of declined transactions to the sum of the amount of total
     * transctions.
     */
    public function getDeclinedAmountPercent(): ?float
    {
        return $this->declinedAmountPercent;
    }

    /**
     * Sets Declined Amount Percent.
     * Ratio of the sum of the amount of declined transactions to the sum of the amount of total
     * transctions.
     *
     * @maps declinedAmountPercent
     */
    public function setDeclinedAmountPercent(?float $declinedAmountPercent): void
    {
        $this->declinedAmountPercent = $declinedAmountPercent;
    }

    /**
     * Returns Chain Code.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related roll-up
     * values under a common identifier for settlement, billing, and reporting. Chain Code is the primary
     * identifier for merchants boarded in a MDB (Merchant Database) system.
     */
    public function getChainCode(): ?string
    {
        return $this->chainCode;
    }

    /**
     * Sets Chain Code.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related roll-up
     * values under a common identifier for settlement, billing, and reporting. Chain Code is the primary
     * identifier for merchants boarded in a MDB (Merchant Database) system.
     *
     * @maps chainCode
     */
    public function setChainCode(?string $chainCode): void
    {
        $this->chainCode = $chainCode;
    }

    /**
     * Returns Store Number.
     * The lowest roll-up level in the hierarchy system, grouping multiple merchant account numbers (MIDs)
     * used in a single merchant location assigned to different terminals and/or business lines (MCCs). A
     * Store Number is nine digits and unique to a particular Chain, meaning the same Store Number can
     * exist for a Store under a different Divison/Chain, but not duplicates under the same Divison/Chain.
     * <br> Supports entities Chain, National.
     */
    public function getStoreNumber(): ?string
    {
        return $this->storeNumber;
    }

    /**
     * Sets Store Number.
     * The lowest roll-up level in the hierarchy system, grouping multiple merchant account numbers (MIDs)
     * used in a single merchant location assigned to different terminals and/or business lines (MCCs). A
     * Store Number is nine digits and unique to a particular Chain, meaning the same Store Number can
     * exist for a Store under a different Divison/Chain, but not duplicates under the same Divison/Chain.
     * <br> Supports entities Chain, National.
     *
     * @maps storeNumber
     */
    public function setStoreNumber(?string $storeNumber): void
    {
        $this->storeNumber = $storeNumber;
    }

    /**
     * Converts the Summary2 object to a human-readable string representation.
     *
     * @return string The string representation of the Summary2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Summary2',
            [
                'approvedCount' => $this->approvedCount,
                'approvedAmount' => $this->approvedAmount,
                'declinedCount' => $this->declinedCount,
                'declinedAmount' => $this->declinedAmount,
                'approvedCountPercent' => $this->approvedCountPercent,
                'approvedAmountPercent' => $this->approvedAmountPercent,
                'declinedCountPercent' => $this->declinedCountPercent,
                'declinedAmountPercent' => $this->declinedAmountPercent,
                'chainCode' => $this->chainCode,
                'storeNumber' => $this->storeNumber,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'approvedCount',
        'approvedAmount',
        'declinedCount',
        'declinedAmount',
        'approvedCountPercent',
        'approvedAmountPercent',
        'declinedCountPercent',
        'declinedAmountPercent',
        'chainCode',
        'storeNumber'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->approvedCount)) {
            $json['approvedCount']         = $this->approvedCount;
        }
        if (isset($this->approvedAmount)) {
            $json['approvedAmount']        = $this->approvedAmount;
        }
        if (isset($this->declinedCount)) {
            $json['declinedCount']         = $this->declinedCount;
        }
        if (isset($this->declinedAmount)) {
            $json['declinedAmount']        = $this->declinedAmount;
        }
        if (isset($this->approvedCountPercent)) {
            $json['approvedCountPercent']  = $this->approvedCountPercent;
        }
        if (isset($this->approvedAmountPercent)) {
            $json['approvedAmountPercent'] = $this->approvedAmountPercent;
        }
        if (isset($this->declinedCountPercent)) {
            $json['declinedCountPercent']  = $this->declinedCountPercent;
        }
        if (isset($this->declinedAmountPercent)) {
            $json['declinedAmountPercent'] = $this->declinedAmountPercent;
        }
        if (isset($this->chainCode)) {
            $json['chainCode']             = $this->chainCode;
        }
        if (isset($this->storeNumber)) {
            $json['storeNumber']           = $this->storeNumber;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
