<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib\Models;

use ReportingAuthorizationSummaryApiLib\ApiHelper;
use stdClass;

class SummaryDetailEntityEntity implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $merchantId;

    /**
     * Returns Merchant Id.
     * The last level in the Vertical Hierarchy and the unique identifier assigned for a processing
     * location, business type, and MCC Code. It requires a specific value to define merchant
     * authorizations, settlement, reporting, pricing, and billing levels.
     */
    public function getMerchantId(): ?string
    {
        return $this->merchantId;
    }

    /**
     * Sets Merchant Id.
     * The last level in the Vertical Hierarchy and the unique identifier assigned for a processing
     * location, business type, and MCC Code. It requires a specific value to define merchant
     * authorizations, settlement, reporting, pricing, and billing levels.
     *
     * @maps merchantId
     */
    public function setMerchantId(?string $merchantId): void
    {
        $this->merchantId = $merchantId;
    }

    /**
     * Converts the SummaryDetailEntityEntity object to a human-readable string representation.
     *
     * @return string The string representation of the SummaryDetailEntityEntity object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SummaryDetailEntityEntity',
            ['merchantId' => $this->merchantId, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['merchantId'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->merchantId)) {
            $json['merchantId'] = $this->merchantId;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
