<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib;

/**
 * Interface for defining the behavior of Authentication.
 */
interface CustomHeaderAuthenticationCredentials
{
    /**
     * String value for authorization.
     */
    public function getAuthorization(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization ``` License format is WORLDPAY license='xxxx'```
     */
    public function equals(string $authorization): bool;
}
