<?php

declare(strict_types=1);

/*
 * ReportingAuthorizationSummaryApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReportingAuthorizationSummaryApiLib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * CCERT Server
     */
    public const PRODUCTION = 'production';
}
